# Generated by Django 4.2.14 on 2025-01-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_user_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="exp",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
