# Generated by Django 4.2.14 on 2025-01-02 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_enable_trigram"),
        ("authentication", "0003_user_exp"),
    ]

    operations = []
