# Generated by Django 4.2.14 on 2025-02-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_remove_user_isonline_user_connect_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='isTwoFa',
            field=models.BooleanField(default=True),
        ),
    ]
