volumes:
  data:

networks:
  ft_transcendence:
    name: ft_transcendence

services:
  frontend:
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
    ports:
      - 3000:3000
    container_name: frontend
    depends_on:
      - backend
    restart: unless-stopped
    user: root # WARNING: For development only
    volumes:
      - ./frontend/public/:/home/app/public:rw
      - ./frontend/src/:/home/app/src:rw
    networks:
        - ft_transcendence

  backend:
    build: 
      context: ./
      dockerfile: ./backend/Dockerfile
    container_name: backend
    env_file:
        - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    user: root # WARNING: For development only
    volumes:
      - ./backend/:/home/app:rw
      - ./logs/uvicorn.log:/var/log/uvicorn/uvicorn.log
    networks:
        - ft_transcendence

  db:
    build:
      context: ./
      dockerfile: ./db/Dockerfile
    healthcheck:
      test: "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
      interval: 5s
      retries: 5
      start_period: 30s
      timeout: 10s
    container_name: db
    env_file:
        - .env
    restart: unless-stopped
    volumes:
      - data:/var/lib/postgresql/data
    networks:
        - ft_transcendence

  redis:
    build:
      context: ./
      dockerfile: ./redis/Dockerfile
    container_name: redis
    env_file:
        - .env
    healthcheck:
      test: "redis-cli -p ${REDIS_PORT} -a ${REDIS_PASSWORD} ping"
      interval: 5s
      retries: 5
      start_period: 30s
      timeout: 10s
    deploy:
      resources:
        limits:
          memory: 512m  # Set the max memory for this container
        reservations:
          memory: 256m  # Set the minimum guaranteed memory
    restart: unless-stopped
    networks:
        - ft_transcendence

  nginx:
    build: 
      context: ./
      dockerfile: ./nginx/Dockerfile
    ports:
      - 8000:8000
    container_name: nginx
    depends_on:
      - backend
    restart: unless-stopped
    volumes:
      - ./backend/static:/home/app/static
      - ./logs/nginx_access.log:/var/log/nginx/access.log
      - ./logs/nginx_errors.log:/var/log/nginx/error.log
    networks:
        - ft_transcendence
