# Generated by Django 4.2.14 on 2024-12-18 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_conversation_receiver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='isBlocked',
            field=models.BooleanField(default=False),
        ),
    ]
