# Generated by Django 4.2.14 on 2024-11-24 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_issent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='isSent',
            field=models.BooleanField(default=True),
        ),
    ]
