# Generated by Django 4.2.14 on 2024-12-18 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_isblocked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='isBlocked',
        ),
        migrations.AddField(
            model_name='conversation',
            name='isBlocked',
            field=models.BooleanField(default=False),
        ),
    ]
