# Generated by Django 4.2.14 on 2024-12-16 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0002_remove_game_description_gameroom_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gameroom",
            name="status",
            field=models.CharField(
                choices=[
                    ("waiting", "Waiting for Players"),
                    ("ongoing", "Game Ongoing"),
                    ("paused", "Game Paused"),
                    ("completed", "Game Completed"),
                    ("expired", "Game Expired"),
                ],
                default="waiting",
                max_length=20,
            ),
        ),
    ]
