# Generated by Django 4.2.14 on 2024-11-24 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_player_rating_gain_player_rating_loss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerrating',
            name='rating',
            field=models.PositiveIntegerField(default=951),
        ),
    ]
