# Generated by Django 4.2.14 on 2024-12-20 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0004_player_ready"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameroom",
            name="state",
            field=models.JSONField(default=dict),
        ),
    ]
