# Generated by Django 4.2.14 on 2024-12-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0008_player_timeouts"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameroom",
            name="turn",
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
