# Generated by Django 4.2.14 on 2024-12-29 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0013_alter_gameroom_paused_at_alter_gameroom_started_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playerachievement",
            name="progress",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
