# Generated by Django 4.2.14 on 2024-12-30 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0014_alter_playerachievement_progress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playerachievement",
            name="earned_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
