# Generated by Django 4.2.14 on 2025-01-08 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0003_tournament_iscanceled"),
        ("games", "0017_alter_gameroom_started_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameroom",
            name="bracket",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tournament.bracket",
            ),
        ),
    ]
