# Generated by Django 4.2.14 on 2025-01-15 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0023_playerrating_rating_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerrating',
            name='limiter',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
