# Generated by Django 4.2.14 on 2025-01-16 13:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0024_playerrating_limiter"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
