# Generated by Django 4.2.14 on 2025-01-16 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0025_player_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playerrating",
            name="losses",
        ),
        migrations.RemoveField(
            model_name="playerrating",
            name="recent_results",
        ),
        migrations.RemoveField(
            model_name="playerrating",
            name="wins",
        ),
    ]
