global:
  scrape_interval: 20s
  evaluation_interval: 20s

alerting:
  alertmanagers:
    - scheme: https
      static_configs:
        - targets:
            - localhost:9093
      tls_config:
        insecure_skip_verify: true

rule_files:
  - '/etc/prometheus/alert_rules.yml'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
    scheme: https
    tls_config:
      insecure_skip_verify: true

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
  
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
