# Generated by Django 4.2.14 on 2025-01-23 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friendship', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendship',
            old_name='friendshipID',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='friendshiprequest',
            old_name='FriendshipRequestID',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='friendshiprequest',
            name='accepted_at',
        ),
        migrations.RemoveField(
            model_name='friendshiprequest',
            name='rejected_at',
        ),
    ]
