# Generated by Django 4.2.14 on 2024-10-28 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friendship', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ManageFriendship',
        ),
    ]
