# Generated by Django 4.2.14 on 2025-01-07 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='isStarted',
            field=models.BooleanField(default=False),
        ),
    ]
