# Generated by Django 4.2.14 on 2025-01-08 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0002_tournament_isstarted"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="isCanceled",
            field=models.BooleanField(default=False),
        ),
    ]
