# Generated by Django 4.2.14 on 2025-01-13 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_tournament_iscanceled'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='tournamentTitle',
            field=models.TextField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
