# Generated by Django 4.2.14 on 2025-01-22 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0007_bracket_iscompleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bracket',
            name='isCompleted',
        ),
    ]
