# Generated by Django 4.2.14 on 2025-01-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0008_remove_bracket_iscompleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="bracket",
            name="player_order",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
