# Generated by Django 4.2.14 on 2025-01-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0010_remove_bracket_player_order_tournamentplayer_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentplayer',
            name='role',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
