# Generated by Django 4.2.14 on 2024-12-28 22:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('notificationId', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('senderUsername', models.CharField(blank=True, max_length=255)),
                ('notifType', models.CharField(choices=[('FR', 'Friend Request'), ('AF', 'Accept Friend Request'), ('IG', 'Invite Game'), ('IT', 'Invite Tournament'), ('ME', 'Message'), ('CC', 'Create Conversation')], max_length=2)),
                ('notifMessage', models.CharField(max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('isRead', models.BooleanField(default=False)),
                ('targetId', models.CharField(blank=True, max_length=255, null=True)),
                ('senderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
