# Generated by Django 4.2.14 on 2024-11-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='isRead',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='notifType',
            field=models.CharField(choices=[('FR', 'Friend Request'), ('IG', 'Invite Game'), ('IT', 'Invite Tournament'), ('ME', 'Message')], max_length=2),
        ),
    ]
