# Generated by Django 4.2.14 on 2024-12-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_alter_notifications_notiftype'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='senderUsername',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
