# Generated by Django 4.2.14 on 2024-12-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0005_notifications_senderusername"),
    ]

    operations = [
        migrations.AddField(
            model_name="notifications",
            name="targetId",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
