# Generated by Django 4.2.14 on 2024-12-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0006_notifications_targetid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notifications",
            name="notifType",
            field=models.CharField(
                choices=[
                    ("FR", "Friend Request"),
                    ("AR", "Accept Friend Request"),
                    ("IG", "Invite Game"),
                    ("IT", "Invite Tournament"),
                    ("ME", "Message"),
                    ("CC", "Create Conversation"),
                ],
                max_length=2,
            ),
        ),
    ]
