# Generated by Django 4.2.14 on 2024-12-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='about',
            field=models.TextField(),
        ),
    ]
