# Generated by Django 4.2.14 on 2024-11-24 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Auth", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="users",
            name="rating",
        ),
    ]
