# Generated by Django 4.2.14 on 2024-12-19 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Auth", "0002_alter_users_about"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="about",
            field=models.TextField(blank=True, null=True),
        ),
    ]
