# Generated by Django 4.2.14 on 2024-08-27 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_users_delete_intrauser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='userID',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
