# Generated by Django 4.2.14 on 2024-11-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_alter_users_first_name_alter_users_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='about',
            field=models.TextField(default='hello i am no one so go hell and take care of yourself '),
        ),
        migrations.AddField(
            model_name='users',
            name='isOnline',
            field=models.BooleanField(default=False),
        ),
    ]
