# Generated by Django 4.2.14 on 2024-12-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_users_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='_2fa',
            field=models.BooleanField(default=True),
        ),
    ]
