# Generated by Django 4.2.14 on 2024-12-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_users_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
