# Generated by Django 4.2.14 on 2024-12-09 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Auth", "0003_users__2fa"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="blockedUsers",
            field=models.JSONField(default={"blockedUsers": []}, null=True),
        ),
    ]
