# Generated by Django 4.2.14 on 2024-11-19 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_users_about_users_isonline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='about',
            field=models.TextField(default='I m an award-winning content writer who has eight years of experience creating compelling articles and short stories. I m continuously searching for new topics and stories to capture the attention of new readers. With my knowledge and experience, I can help you fulfill your content creation goals.'),
        ),
    ]
