# Generated by Django 4.2.14 on 2024-09-13 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0004_alter_users_options_alter_users_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='users',
            managers=[
            ],
        ),
    ]
