# Generated by Django 4.2.14 on 2024-11-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0004_alter_users_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='isTwoFa',
            field=models.BooleanField(default=False),
        ),
    ]
