# Generated by Django 4.2.14 on 2024-12-23 21:30

import Auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Auth", "0004_alter_users_about"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="blockedUsers",
            field=models.JSONField(
                blank=True, default=Auth.models.callableDict, null=True
            ),
        ),
    ]
