# Generated by Django 4.2.14 on 2024-12-09 18:04

import Auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0004_users_blockedusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='blockedUsers',
            field=models.JSONField(default=Auth.models.callableDict, null=True),
        ),
    ]
