# Generated by Django 4.2.14 on 2024-12-15 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Auth", "0003_users_last_update"),
        ("Auth", "0005_alter_users_blockedusers"),
    ]

    operations = []
